authors:
  essex:
    name: Essex
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/41241945
    url: https://github.com/essexhardmonkey
  maruski:
    name: Maruski
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/41241945
    url: hhttps://github.com/essexhardmonkey
