authors:
  essex:
    name: Essex
    description: Developper
    avatar: https://avatars.githubusercontent.com/u/932156
    url: https://github.com/squidfunk
  maruski:
    name: Maruski
    description: Developere
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss
